In [2]:
## Basic Modules to Import in Each Notebook

%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import os

In [3]:
df = pd.read_csv("combined2.csv")
df.head()

,id,sex,age,age_cat,race,juve_fel_count,decile_score,juv_misd_count,juv_other_count,prios_count,...,decile_score_a,score_text,v_type_of_assessment,v_decile_score_v,v_score_text,priors_count,start,end_,event,two_year_recid
0,1,Male,69,Greater than 45,Other,0,1,0,0,0,...,1,Low,Risk of Violence,1,Low,0,0,327,0,0
1,3,Male,34,25 - 45,African-American,0,3,0,0,0,...,3,Low,Risk of Violence,1,Low,0,9,159,1,1
2,4,Male,24,Less than 25,African-American,0,4,0,1,4,...,4,Low,Risk of Violence,3,Low,4,0,63,0,1
3,5,Male,23,Less than 25,African-American,0,8,1,0,1,...,8,High,Risk of Violence,6,Medium,1,0,1174,0,0
4,6,Male,43,25 - 45,Other,0,1,0,0,2,...,1,Low,Risk of Violence,1,Low,2,0,1102,0,0

In [4]:
# for col in df.columns: 
#     print(col)

In [5]:
caucasian = df.loc[df['race'] == 'Caucasian']
caucasian.head()

,id,sex,age,age_cat,race,juve_fel_count,decile_score,juv_misd_count,juv_other_count,prios_count,...,decile_score_a,score_text,v_type_of_assessment,v_decile_score_v,v_score_text,priors_count,start,end_,event,two_year_recid
6,8,Male,41,25 - 45,Caucasian,0,6,0,0,14,...,6,Medium,Risk of Violence,2,Low,14,5,40,1,1
8,10,Female,39,25 - 45,Caucasian,0,1,0,0,0,...,1,Low,Risk of Violence,1,Low,0,2,747,0,0
9,13,Male,21,Less than 25,Caucasian,0,3,0,0,1,...,3,Low,Risk of Violence,5,Medium,1,0,428,1,1
10,14,Male,27,25 - 45,Caucasian,0,4,0,0,0,...,4,Low,Risk of Violence,4,Low,0,0,857,0,0
12,16,Female,37,25 - 45,Caucasian,0,1,0,0,0,...,1,Low,Risk of Violence,1,Low,0,1,1186,0,0

In [ ]:
## DF for earliest trials, not separating age category 
caucasian_DF = pd.get_dummies(caucasian)
caucasian_DF.head()

In [ ]:
caucasian_small = caucasian_DF[['age', 'juve_fel_count', 'priors_count', 'violence', 'drugs', 'theft', 'arrest_case_no_charge', 'traffic', 'disorderly_conduct', 'sexual_misconduct', 'sex_Female', 'sex_Male', 'two_year_recid']]
caucasian_small.head()

In [ ]:
# for col in caucasian_small.columns: 
#     print(col)

In [6]:
## adding a new small df that makes dummies for age cateogry hopefully
caucasian_reduced = caucasian[['sex', 'age', 'age_cat', 'juve_fel_count', 'priors_count', 'violence', 'drugs', 'theft', 'arrest_case_no_charge', 'traffic', 'disorderly_conduct', 'sexual_misconduct','two_year_recid','juv_misd_count', 'prios_count']]
caucasian_reduced.head()

,sex,age,age_cat,juve_fel_count,priors_count,violence,drugs,theft,arrest_case_no_charge,traffic,disorderly_conduct,sexual_misconduct,two_year_recid,juv_misd_count,prios_count
6,Male,41,25 - 45,0,14,0,0,5,0,0,0,0,1,0,14
8,Female,39,25 - 45,0,0,7,0,0,0,0,0,0,0,0,0
9,Male,21,Less than 25,0,1,0,0,5,0,0,0,0,1,0,1
10,Male,27,25 - 45,0,0,0,6,0,0,0,0,0,0,0,0
12,Female,37,25 - 45,0,0,7,0,0,0,0,0,0,0,0,0

In [7]:
caucasian_DF = pd.get_dummies(caucasian_reduced)
caucasian_DF.head()

,age,juve_fel_count,priors_count,violence,drugs,theft,arrest_case_no_charge,traffic,disorderly_conduct,sexual_misconduct,two_year_recid,juv_misd_count,prios_count,sex_Female,sex_Male,age_cat_25 - 45,age_cat_Greater than 45,age_cat_Less than 25
6,41,0,14,0,0,5,0,0,0,0,1,0,14,0,1,1,0,0
8,39,0,0,7,0,0,0,0,0,0,0,0,0,1,0,1,0,0
9,21,0,1,0,0,5,0,0,0,0,1,0,1,0,1,0,0,1
10,27,0,0,0,6,0,0,0,0,0,0,0,0,0,1,1,0,0
12,37,0,0,7,0,0,0,0,0,0,0,0,0,1,0,1,0,0

## Train Specifically From Caucasian Filtered

In [ ]:
X = caucasian_small[['age', 'juve_fel_count', 'priors_count', 'violence', 'drugs', 'theft', 'arrest_case_no_charge', 'traffic', 'disorderly_conduct', 'sexual_misconduct', 'sex_Female', 'sex_Male']]
y = caucasian_small['two_year_recid'].values.reshape(-1, 1)

In [ ]:
X_train_caucasian = caucasian_small[['age', 'juve_fel_count', 'priors_count', 'violence', 'drugs', 'theft', 'arrest_case_no_charge', 'traffic', 'disorderly_conduct', 'sexual_misconduct', 'sex_Female', 'sex_Male']]
# y_train_caucasian = caucasian_small['two_year_recid'].values.reshape(-1, 1)
y_train_caucasian = caucasian_small['two_year_recid']

# print(X_train, y_train)

## More robust one

In [8]:
X_train_caucasian = caucasian_DF[['juve_fel_count', 'priors_count', 'violence', 'drugs', 'theft', 'arrest_case_no_charge', 'traffic', 'disorderly_conduct', 'sexual_misconduct', 'sex_Female', 'sex_Male', 'age_cat_25 - 45', 'age_cat_Greater than 45', 'age_cat_Less than 25', 'juv_misd_count', 'prios_count']]
# y_train_caucasian = caucasian_DF['two_year_recid'].values.reshape(-1, 1)
y_train_caucasian = caucasian_DF['two_year_recid']

## Filter by A-A so that we can then create a test set

In [11]:
african_american = df.loc[df['race'] == 'African-American']
# african_american.head()

In [ ]:
african_american_DF = pd.get_dummies(african_american)
# african_american_DF.head()

In [ ]:
african_american_small = african_american_DF[['age', 'juve_fel_count', 'priors_count', 'violence', 'drugs', 'theft', 'arrest_case_no_charge', 'traffic', 'disorderly_conduct', 'sexual_misconduct', 'sex_Female', 'sex_Male', 'two_year_recid']]
# african_american_small.head()

In [ ]:
X_test_aa = african_american_small[['age', 'juve_fel_count', 'priors_count', 'violence', 'drugs', 'theft', 'arrest_case_no_charge', 'traffic', 'disorderly_conduct', 'sexual_misconduct', 'sex_Female', 'sex_Male']]
# y_test_aa = african_american_small['two_year_recid'].values.reshape(-1, 1)
y_test_aa = african_american_small['two_year_recid']

In [9]:
##------------------------------------- New Stuff To Use and Compare

In [12]:
## adding a new small df that makes dummies for age cateogry hopefully
african_american_reduced = african_american[['sex', 'age', 'age_cat', 'juve_fel_count', 'priors_count', 'violence', 'drugs', 'theft', 'arrest_case_no_charge', 'traffic', 'disorderly_conduct', 'sexual_misconduct','two_year_recid','juv_misd_count', 'prios_count']]
# african_american_reduced.head()

In [13]:
african_american_DF = pd.get_dummies(african_american_reduced)
# african_american_DF.head()

In [14]:
X_test_aa = african_american_DF[['juve_fel_count', 'priors_count', 'violence', 'drugs', 'theft', 'arrest_case_no_charge', 'traffic', 'disorderly_conduct', 'sexual_misconduct', 'sex_Female', 'sex_Male', 'age_cat_25 - 45', 'age_cat_Greater than 45', 'age_cat_Less than 25', 'juv_misd_count', 'prios_count']]
# y_test_aa = african_american_DF['two_year_recid'].values.reshape(-1, 1)
y_test_aa = african_american_DF['two_year_recid']

## Doing Tests With White Train vs. A-A Test

In [18]:
from sklearn.ensemble import RandomForestClassifier
# this was 200 earlier
rf = RandomForestClassifier(n_estimators=1000)
rf = rf.fit(X_train_caucasian, y_train_caucasian)
rf.score(X_test_aa, y_test_aa)

0.6262214983713354

In [19]:
feature_names = X_train_caucasian.columns
sorted(zip(rf.feature_importances_, feature_names), reverse=True)

[(0.24938164059660936, 'prios_count'),
 (0.24714857523157235, 'priors_count'),
 (0.06065282088967009, 'age_cat_Greater than 45'),
 (0.05003726614419836, 'juv_misd_count'),
 (0.046335273848247864, 'theft'),
 (0.03864232058050758, 'drugs'),
 (0.03700257492224101, 'age_cat_Less than 25'),
 (0.036748952614912615, 'traffic'),
 (0.035675568481983874, 'violence'),
 (0.0351477053675708, 'sex_Female'),
 (0.03514071157419756, 'sex_Male'),
 (0.03466437401432482, 'age_cat_25 - 45'),
 (0.03340923965383522, 'arrest_case_no_charge'),
 (0.028253652340290186, 'disorderly_conduct'),
 (0.024007274179246932, 'juve_fel_count'),
 (0.00775204956059137, 'sexual_misconduct')]

## Testing with more rf stuff

In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.datasets import make_blobs
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.tree import DecisionTreeClassifier

X_train_caucasian, y_train_caucasian = make_blobs(n_samples=10000, n_features=10, centers=100,
    random_state=0)

In [ ]:
clf = DecisionTreeClassifier(max_depth=None, min_samples_split=2,
    random_state=0)
scores = cross_val_score(clf, X_train_caucasian, y_train_caucasian, cv=5)
scores.mean()

In [ ]:
clf = RandomForestClassifier(n_estimators=10, max_depth=None,
    min_samples_split=2, random_state=0)
scores = cross_val_score(clf, X_train_caucasian, y_train_caucasian, cv=5)
scores.mean()

In [ ]:

clf = ExtraTreesClassifier(n_estimators=10, max_depth=None,
    min_samples_split=2, random_state=0)
scores = cross_val_score(clf, X_train_caucasian, y_train_caucasian, cv=5)
scores.mean() > 0.999

## Try to Train Test With Caucasian

In [138]:
from sklearn.model_selection import train_test_split
from sklearn import tree
X_train, X_test, y_train, y_test = train_test_split(X_train_caucasian, y_train_caucasian, random_state=42)

In [142]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=8000)
rf = rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.630718954248366

In [143]:
print(f"Training Data Score: {rf.score(X_train, y_train)}")
print(f"Testing Data Score: {rf.score(X_test, y_test)}")

Training Data Score: 0.7545008183306056
Testing Data Score: 0.630718954248366

In [ ]:
rf

In [ ]:
X_test

In [144]:
predictions = rf.predict(X_test)

In [145]:
predictions

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0], dtype=int64)

In [146]:
pd.DataFrame({"Prediction": predictions, "Actual": y_test}).reset_index(drop=True)

     Prediction  Actual
0             0       0
1             1       0
2             0       1
3             1       1
4             0       1
5             1       1
6             0       1
7             1       0
8             0       0
9             0       0
10            0       0
11            0       1
12            0       0
13            0       0
14            0       1
15            0       0
16            1       0
17            0       0
18            0       1
19            1       0
20            0       0
21            1       0
22            0       0
23            0       1
24            0       0
25            0       0
26            0       0
27            0       1
28            0       1
29            0       1
..          ...     ...
582           0       0
583           1       0
584           0       1
585           0       0
586           0       0
587           0       1
588           0       0
589           0       0
590           0       0
591           0       0
592           0       0
593           0       0
594           0       0
595           0       0
596           1       1
597           0       1
598           0       1
599           0       1
600           0       0
601           0       1
602           0       0
603           0       1
604           0       0
605           0       0
606           0       0
607           0       0
608           0       0
609           0       1
610           1       0
611           0       0

[612 rows x 2 columns]

##

In [ ]:
feature_names = X.columns

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=200)
rf = rf.fit(X_train, y_train)
rf.score(X_test, y_test)

In [ ]:
sorted(zip(rf.feature_importances_, feature_names), reverse=True)

## Test White non scaled vs AA non scaled

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=200)
rf = rf.fit(X_train_caucasian, y_train_caucasian)
rf.score(X_test_aa, y_test_aa)

In [ ]:
# test_scores = []
# x = 0 
# while x != 10:
#     rf = RandomForestClassifier(n_estimators=200)
#     rf = rf.fit(X_train_caucasian, y_train_caucasian)
#     rf.score(X_test_aa, y_test_aa)  
#     test_scores.append(rf.score(X_test_aa, y_test_aa))
#     x = x + 1

In [ ]:
# test_scores

## Train Test with Added Juv Misd Count, Prios Count

## Train White Test Black

In [ ]:
X_train_caucasian = caucasian_DF[['age', 'juve_fel_count', 'priors_count', 'violence', 'drugs', 'theft', 'arrest_case_no_charge', 'traffic', 'disorderly_conduct', 'sexual_misconduct', 'sex_Female', 'sex_Male', 'juv_misd_count', 'prios_count']]
y_train_caucasian = caucasian_DF['two_year_recid'].values.reshape(-1, 1)
# X_train_caucasian

In [ ]:
X_test_aa = african_american_DF[['age', 'juve_fel_count', 'priors_count', 'violence', 'drugs', 'theft', 'arrest_case_no_charge', 'traffic', 'disorderly_conduct', 'sexual_misconduct', 'sex_Female', 'sex_Male', 'juv_misd_count', 'prios_count']]
y_test_aa = african_american_DF['two_year_recid'].values.reshape(-1, 1)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=200)
rf = rf.fit(X_train_caucasian, y_train_caucasian)
rf.score(X_test_aa, y_test_aa)

In [ ]:
feature_names = X_train_caucasian

In [ ]:
sorted(zip(rf.feature_importances_, feature_names), reverse=True)

##### Train White Scaled vs AA Scaled

In [ ]:
from sklearn.preprocessing import StandardScaler

# Create a StandardScater model and fit it to the training data

### BEGIN SOLUTION
X_scaler = StandardScaler().fit(X_train_caucasian)
y_scaler = StandardScaler().fit(y_train_caucasian)
### END SOLUTION

In [ ]:
# Transform the training and testing data using the X_scaler and y_scaler models

### BEGIN SOLUTION
X_train_scaled = X_scaler.transform(X_train_caucasian)
X_test_scaled = X_scaler.transform(X_test_aa)
y_train_scaled = y_scaler.transform(y_train_caucasian)
y_test_scaled = y_scaler.transform(y_test_aa)
### END SOLUTION

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=200)
rf = rf.fit(X_train_scaled, y_train_scaled)
rf.score(X_test_scaled, y_test_scaled)

## Test AA vs AA

In [ ]:
X_train_aa = african_american_small[['age', 'juve_fel_count', 'priors_count', 'violence', 'drugs', 'theft', 'arrest_case_no_charge', 'traffic', 'disorderly_conduct', 'sexual_misconduct', 'sex_Female', 'sex_Male']]
y_train_aa = african_american_small['two_year_recid'].values.reshape(-1, 1)

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn import tree
X_train, X_test, y_train, y_test = train_test_split(X_train_aa, y_train_aa, random_state=42)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=200)
rf = rf.fit(X_train, y_train)
rf.score(X_test, y_test)

## Train AA

## Miscellaneous

## Import Mean Squared Error for Measures

In [ ]:
# Create a LinearRegression model and fit it to the scaled training data

### BEGIN SOLUTION
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train_scaled, y_train_scaled)
### END SOLUTION

# Used X_test_scaled, y_test_scaled, and model.predict(X_test_scaled) to calculate MSE and R2

### BEGIN SOLUTION
from sklearn.metrics import mean_squared_error

MSE = mean_squared_error(y_test, predictions)
r2 = model.score(X_test, y_test)
### END SOLUTION

print(f"MSE: {MSE}, R2: {r2}")

In [ ]:
# ElasticNet model
# Note: Use an alpha of .01 when creating the model for this activity
from sklearn.linear_model import ElasticNet

### BEGIN SOLUTION
elasticnet = ElasticNet(alpha=.01).fit(X_train_scaled, y_train_scaled)

predictions = elasticnet.predict(X_test_scaled)

MSE = mean_squared_error(y_test_scaled, predictions)
r2 = elasticnet.score(X_test_scaled, y_test_scaled)
### END SOLUTION

print(f"MSE: {MSE}, R2: {r2}")

In [ ]:
# LASSO model
# Note: Use an alpha of .01 when creating the model for this activity
from sklearn.linear_model import Lasso

### BEGIN SOLUTION
lasso = Lasso(alpha=.01).fit(X_train_scaled, y_train_scaled)

predictions = lasso.predict(X_test_scaled)

MSE = mean_squared_error(y_test_scaled, predictions)
r2 = lasso.score(X_test_scaled, y_test_scaled)
### END SOLUTION

print(f"MSE: {MSE}, R2: {r2}")